### PR TITLE
Support trace information in logs

### PR DESCRIPTION
**Pull request by caskolkm**
Hi Guys, I added functionality to support trace information in the logs.

See: https://cloud.google.com/logging/docs/agent/configuration#special-fields

### CODE REVIEW

**Comment by JeanMertz** [comment]
Thank you for your contribution @caskolkm!

Regarding the string format `TRACE_ID/SPAN_ID;o=TRACE_TRUE`, is this a standard trace format definition? I couldn't find anything relevant other than [this Google Cloud](https://cloud.google.com/trace/docs/troubleshooting#force-trace) page talking about adding trace information using headers.

In that case, it makes sense to use such a format, as it adheres to best practices on how to format a header, and a header can only be a single string.

In the case of this library though, unless there is a compelling reason to stick to the current format, I think it would be best if we moved away from the regex implementation, and used a typed function signature for improved performance (no regex parsing) and correctness (the function becomes infallible).

So instead of this:

```go
func TraceContext(traceContext string, projectName string) []zap.Field
```

We'd use this:

```go
func TraceContext(trace string, spanID string, sampled bool, projectName string) []zap.Field
```

Given your example, we'd get:

```go
// before
TraceContext("105445aa7843bc8bf206b120001000/0;o=1", "my-project-name")

// after
TraceContext("105445aa7843bc8bf206b120001000", "0", true, "my-project-name")
```

WDYT?

**Comment by caskolkm** [comment]
@JeanMertz i thought it was a standard trace format, but i can agree on your suggestion.

**Comment by caskolkm** [comment]
@JeanMertz changed the implementation, take a look :)

**Comment by JeanMertz** [comment]
@caskolkm looks great, thanks! I tested it locally (I should really add CI integration to this repository) and it works as expected 👍. I'll cut a new release with this change included.

**Comment by caskolkm** [comment]
@JeanMertz you are fast! thnx!

**Pull request merged**
